#!/bin/bash
wp plugin --allow-root install autoptimize
wp plugin --allow-root install block-bad-queries
wp plugin --allow-root install caldera-forms
wp plugin --allow-root install duplicate-post
wp plugin --allow-root install fast-page-switch
wp plugin --allow-root install format-media-titles
wp plugin --allow-root install imsanity
wp plugin --allow-root install updraftplus
wp plugin --allow-root install wp-smushit
wp plugin --allow-root install wp-seopress
wp plugin --allow-root install secupress
wp plugin --allow-root install gutenberg
wp plugin --allow-root install polylang
wp plugin --allow-root install gutenberg
wp plugin --allow-root install companion-auto-update
wp plugin --allow-root install advanced-custom-fields
wp plugin --allow-root install wp-pagenavi
wp plugin --allow-root activate --all