#!/bin/bash
php wp-cli.phar plugin install autoptimize
php wp-cli.phar plugin install block-bad-queries
php wp-cli.phar plugin install caldera-forms
php wp-cli.phar plugin install duplicate-post
php wp-cli.phar plugin install fast-page-switch
php wp-cli.phar plugin install format-media-titles
php wp-cli.phar plugin install imsanity
php wp-cli.phar plugin install updraftplus
php wp-cli.phar plugin install wp-smushit
php wp-cli.phar plugin install wp-seopress
php wp-cli.phar plugin install secupress
php wp-cli.phar plugin install gutenberg
php wp-cli.phar plugin install polylang
php wp-cli.phar plugin install gutenberg
php wp-cli.phar plugin install companion-auto-update
php wp-cli.phar plugin install advanced-custom-fields
php wp-cli.phar plugin install wp-pagenavi
php wp-cli.phar plugin activate --all